/*=============================================================================
  Copyright (c) 2010-2014 Bolero MURAKAMI
  https://github.com/bolero-MURAKAMI/Sprig

  Distributed under the Boost Software License, Version 1.0. (See accompanying
  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/
#ifndef SPRIG_CONFIG_LIB_OPENCV_HPP
#define SPRIG_CONFIG_LIB_OPENCV_HPP

#ifdef SPRIG_CONFIG_LIB_USERCONFIG
#	include "../../../config/libconfig/opencv.hpp"
#endif	// #ifdef SPRIG_CONFIG_LIB_USERCONFIG

#include <sprig/config/pragma_once.hpp>

#ifdef SPRIG_USING_PRAGMA_ONCE
#	pragma once
#endif	// #ifdef SPRIG_USING_PRAGMA_ONCE

#ifdef SPRIG_CONFIG_LIB_AUTO_LINK

#ifndef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CORE_LIB
#			define SPRIG_LIBCONFIG_OPENCV_CORE_BINARY SPRIG_LIBCONFIG_OPENCV_CORE_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CORE_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CORE_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_CORE_BINARY SPRIG_LIBCONFIG_OPENCV_CORE_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CORE_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB
#			define SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB
#			define SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB
#			define SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_LIB
#			define SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY SPRIG_LIBCONFIG_OPENCV_FLANN_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY SPRIG_LIBCONFIG_OPENCV_FLANN_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB
#			define SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB
#			define SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_GPU_LIB
#			define SPRIG_LIBCONFIG_OPENCV_GPU_BINARY SPRIG_LIBCONFIG_OPENCV_GPU_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_GPU_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_GPU_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_GPU_BINARY SPRIG_LIBCONFIG_OPENCV_GPU_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_GPU_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB
#			define SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_ML_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_ML_LIB
#			define SPRIG_LIBCONFIG_OPENCV_ML_BINARY SPRIG_LIBCONFIG_OPENCV_ML_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_ML_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_ML_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_ML_BINARY SPRIG_LIBCONFIG_OPENCV_ML_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_ML_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_ML_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB
#			define SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB
#			define SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY
#	ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB
#			define SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB
#	else	// #ifdef NDEBUG
#		ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB_D
#			define SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB_D
#		endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_LIB_D
#	endif	// #ifdef NDEBUG
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY

#ifndef SPRIG_LIBCONFIG_OPENCV_TS_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_TS_LIB
#		define SPRIG_LIBCONFIG_OPENCV_TS_BINARY SPRIG_LIBCONFIG_OPENCV_TS_LIB
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_TS_LIB
#endif	// #ifndef SPRIG_LIBCONFIG_OPENCV_TS_BINARY

#include <boost/preprocessor/stringize.hpp>
#include <sprig/config/pragma_comment.hpp>

#ifdef SPRIG_HAS_PRAGMA_COMMENT
#	ifdef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CORE_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_GPU_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_ML_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_ML_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_ML_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_TS_BINARY
#		pragma comment(lib, BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_TS_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_TS_BINARY
#endif	// #ifdef SPRIG_HAS_PRAGMA_COMMENT

#include <sprig/config/pragma_message.hpp>

#ifdef SPRIG_HAS_PRAGMA_MESSAGE
#	pragma message("sprig/config/lib/opencv.hpp")
#	ifdef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CORE_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CORE_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_IMAGEPROC_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CONTRIB_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_LEGACY_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FLANN_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FEATURES2D_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_CALIB3D_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_GPU_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_GPU_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_OBJDETECT_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_ML_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_ML_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_ML_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_VIDEO_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_FFMPEG_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_HIGHGUI_BINARY
#	ifdef SPRIG_LIBCONFIG_OPENCV_TS_BINARY
#		pragma message("    lib=" BOOST_PP_STRINGIZE(SPRIG_LIBCONFIG_OPENCV_TS_BINARY))
#	endif	// #ifdef SPRIG_LIBCONFIG_OPENCV_TS_BINARY
#endif	// #ifdef SPRIG_HAS_PRAGMA_MESSAGE

#endif	// #ifdef SPRIG_CONFIG_LIB_AUTO_LINK

#include <sprig/config/libinfo/opencv.hpp>

#endif	// #ifndef SPRIG_CONFIG_LIB_OPENCV_HPP
